---
all:
  hosts:
    app:
      ansible_host: 2.28.26.25
      # The "admin" user is created by cloud-init (user_data in iac/main.tf),
      # so the playbook always runs as admin on port 3254 - no root phase.
      ansible_user: admin
      ansible_port: 3254
